routes/admin.php
<?php

Route::group(['prefix'  =>  'admin'], function () {
    Route::get('login', 'Admin\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Admin\LoginController@login')->name('admin.login.post');
    Route::get('logout', 'Admin\LoginController@logout')->name('admin.logout');
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/', function () {
            return view('admin.dashboard.index');
        })->name('admin.dashboard');
        Route::get('/settings', 'Admin\SettingController@index')->name('admin.settings');
        Route::post('/settings', 'Admin\SettingController@update')->name('admin.settings.update');
    });
});

Route::group(['middleware' => ['auth:admin'], 'prefix'  =>  'admin'], function () {

Route::resource('user','Admin\UserController')->except('show');
Route::resource('email','Admin\EmailController')->except('show');
Route::resource('memail','Admin\MemailController')->except('show');
Route::resource('attribute','Admin\AttributeController')->except('show');
Route::resource('attributevalue', 'Admin\AttributevalueController')->except('show');
Route::resource('amenity', 'Admin\AmenityController')->except('show');
Route::resource('productattribute', 'Admin\ProductattributeController')->except('show');

//Product Admin Controller
Route::resource('orders', 'Admin\OrderController');
Route::resource('product', 'Admin\ProductController')->except('show');
Route::resource('category', 'Admin\CategoryController')->except('show');
Route::resource('contact', 'Admin\ContactController')->except('show');
Route::resource('cities', 'Admin\CityController')->except('show');
Route::resource('adtype', 'Admin\AdtypeController')->except('show');
Route::resource('day', 'Admin\DayController')->except('show');
Route::resource('report', 'Admin\ReportController')->except('show');
Route::resource('pricetype', 'Admin\PricetypeController')->except('show');
Route::resource('bid','Admin\BidController')->except('show');
Route::resource('reportname', 'Admin\ReportnameController')->except('show');
Route::resource('condition', 'Admin\ConditionController')->except('show');
Route::resource('experience', 'Admin\ExperienceController');
//blog Controller
Route::resource('post', 'Admin\PostController')->except('show');
Route::resource('author', 'Admin\AuthorController')->except('show');
Route::resource('mcategory', 'Admin\McategoryController')->except('show');
Route::resource('tag', 'Admin\TagController')->except('show');
// Job Admin Controller
Route::resource('job', 'Admin\JobController')->except('show');
Route::resource('jobtype', 'Admin\JobtypeController')->except('show');
Route::resource('salarytype', 'Admin\SalarytypeController')->except('show');
Route::resource('jobcategory', 'Admin\JobcategoryController')->except('show');
Route::resource('industry', 'Admin\IndustryController')->except('show');
Route::resource('skill', 'Admin\SkillController')->except('show');
Route::resource('level', 'Admin\LevelController')->except('show');
Route::resource('positiontype', 'Admin\PositiontypeController')->except('show');
Route::resource('comment','Admin\CommentController')->except('show');
Route::resource('bid','Admin\BidController')->except('show', 'update');
Route::resource('resume', 'Admin\ResumeController')->except('show');

Route::resource('address', 'Admin\AddressController')->except('show');
Route::resource('courier', 'Admin\CourierController')->except('show');
Route::resource('orderstatus', 'Admin\OrderStatusController')->except('show');
Route::resource('pricelabel', 'Admin\PricelabelController')->except('show');

Route::resource('follower', 'Admin\FollowerController')->except('show','store');
Route::resource('wishlist', 'Admin\WishlistController')->except('show','destroy','store');

Route::resource('profiles', 'Admin\ProfileController')->except('show','store');
Route::resource('education', 'Admin\EducationController')->except('show','store');
Route::resource('applicant', 'Admin\ApplicantController')->except('show','store','create');
Route::resource('work', 'Admin\WorkController')->except('show','store','create');
Route::resource('training', 'Admin\TrainingController')->except('show','store','create');
Route::resource('partner', 'Admin\PartnerController')->except('show');
Route::resource('firmusers','Admin\FirmuserController')->except('show');
Route::resource('mcontact', 'Admin\McontactController')->except('show','store');

Route::resource('fcategory', 'Admin\FcategoryController')->except('show');
Route::resource('fjob', 'Admin\FjobController')->except('show');
Route::resource('assured', 'Admin\AssuredController')->except('show');
});

Route::group(['middleware' => ['auth:admin'],'prefix' => 'api'], function() {
    Route::post('category/save_orders', 'Admin\CategoryController@saveOrders');
    Route::post('partner/save_orders', 'Admin\PartnerController@saveOrders');
    Route::post('product/save_orders', 'Admin\ProductController@saveOrders');
    Route::post('post/save_orders', 'Admin\PostController@saveOrders');
    Route::post('jobcategory/save_orders', 'Admin\JobcategoryController@saveOrders');
    Route::post('job/save_orders', 'Admin\JobController@saveOrders');
    Route::post('attribute/save_orders', 'Admin\AttributeController@saveOrders');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);
require 'admin.php';
//frontend routes
Route::get('/', 'Site\FrontendController@index')->name('index');
Route::get('category/{category}', 'Site\FrontendController@menu')->name('menu');
Route::get('city/{slug}', 'Site\FrontendController@findByCity')->name('findByCity');
Route::get('user/{slug}', 'Site\FrontendController@user')->name('user');
Route::get('ad/{slug}', 'Site\AdshowController@product_details')->name('product_details');

Route::get('search-product', 'Site\AdshowController@searchProduct')->name('search-product');
Route::get('all-categories', 'Site\FrontendController@allCategories');
//blogshow
Route::get('blog/{slug}', 'Site\BlogController@show')->name('blog');
Route::get('blog', 'Site\BlogController@all')->name('blog.all');
Route::get('blog/category/{slug}', 'Site\BlogController@findByBlogCategory')->name('blog.category');
Route::get('blog/tag/{slug}', 'Site\BlogController@findByTag')->name('blog.tag');

Route::get('sold_action', 'Site\AdminController@sold_action')->name('sold_action');

//AdminPanel
Route::group(['middleware' => ['auth', 'verified']], function () {

    Route::get('addSeller', 'Site\FollowerController@addSeller')->name('addSeller');
    /*Route::get('companyFollow', 'Site\FollowerController@companyFollow')->name('companyFollow');
    Route::get('follow', 'Site\FollowerController@index')->name('follow');
    Route::delete('follow/destroy', 'Site\FollowerController@destroy')->name('follow.destroy');*/
    Route::get('submit-ad', 'Site\AdminController@submitAd')->name('submit-ad');
    // Route::get('submit-ad', 'Site\SearchController@storeAd')->name('storeAd');
    Route::get('submit-ad-photo/{id}', 'Site\AdminController@submitAdPhoto')->name('submit-ad-photo');
    Route::get('submit-ad-edit/{id}', 'Site\AdminController@submitAdEdit')->name('submit-ad-edit');
    Route::post('product-store', 'Site\AdminController@productStore')->name('product-store');
    Route::patch('update-product/{id}', 'Site\AdminController@updateProduct')->name('update-product');
    Route::delete('product-delete/{id}', 'Site\AdminController@deleteProduct')->name('product-delete');
    Route::get('inbox', 'Site\AdminController@inbox')->name('inbox');
    Route::get('profile', 'Site\AdminController@profile')->name('profile');
    Route::get('user-all-ads', 'Site\AdminController@userAllAds')->name('user-all-ads');

    Route::get('favourite-ads', 'Site\AdminController@favouriteAds')->name('favourite-ads');
    Route::delete('wishlist/{id}', 'Site\WishlistController@destroy')->name('wishlist.destroy');
    Route::get('edit-profile', 'Site\AdminController@editProfile')->name('edit-profile');
    Route::patch('updateProfile', 'Site\AdminController@updateProfile')->name('updateProfile');
    Route::get('user-resumes', 'Site\AdminController@userResumes')->name('user-resumes');

    Route::post('/reply/store', 'Site\CommentController@replyStore')->name('reply.add');
    Route::post('comment-store', 'Site\CommentController@storeComment')->name('comment-store');
    Route::post('bid-store', 'Site\BidController@storeBid')->name('bid-store');
});

Route::post('contact-store', 'Site\ContactController@storeContact')->name('contact-store');
Route::post('report-store', 'Site\ReportController@storeReport')->name('report-store');
//jobs
Route::get('jobs', 'Site\JobController@index')->name('jobs');
Route::get('all-jobcategories', 'Site\JobController@allJobCategories')->name('all-jobcategories');
Route::get('all-jobs', 'Site\JobController@allJobs')->name('all-jobs');
Route::get('jobs/category/{slug}', 'Site\JobController@jobCat')->name('jobcat');
Route::get('jobs/city/{slug}', 'Site\JobController@jobCity')->name('jobcity');
Route::get('jobs/user/{id}', 'Site\JobController@findByCompany')->name('jobuser');
Route::get('jobs/type/{slug}', 'Site\JobController@findByJobType')->name('jobtype');
Route::get('jobs/skill/{slug}', 'Site\JobController@jobSkill')->name('jobskill');
Route::get('search-job', 'Site\JobController@searchJob')->name('search-job');
Route::post('create-resume', 'Site\AdminController@createResume')->name('create-resume');
// Job Controller
Route::resource('job-user', 'Site\JobuserController')->except('show');

Route::get('addToLove', 'Site\WishlistController@post_wishlist')->name('addToLove');
// Freelancer Controller
Route::get('jobs/{slug}', 'Site\JobController@jobShow')->name('job_post');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::post('/profile/store', 'Site\FreelancerController@storeProfile');
    Route::post('/profile/edit', 'Site\FreelancerController@updateProfile');
    Route::post('/profile/uploadphoto', 'Site\FreelancerController@uploadPhoto');
    Route::post('/profile/updatephoto', 'Site\FreelancerController@updatePhoto');
    Route::get('/profile/{name}', 'Site\FreelancerController@profile');
    Route::get('/my-jobs', 'Site\FreelancerController@myJobs');

    Route::get('/job/application/{id}', 'Site\ApplicantController@show');
    Route::post('/job/application/{id}/store', 'Site\ApplicantController@store');
});

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/applicant/profile/{id}', 'Site\ApplicantController@view');
});
// Client Controller
Route::get('/dashboard', 'Site\ClientController@dashboard');
Route::get('/shortlist/{slug}', 'Site\ClientController@shortlist');
Route::get('/proposal/{slug}/{user_id}', 'Site\ClientController@proposal');
Route::get('/proposal/{id}/{user}/hire', 'Site\ClientController@hire');
Route::get('/proposal/{id}/{user}/reject', 'Site\ClientController@reject');
Route::get('/editfirmuser', 'Site\ClientController@editfirmuser')->name('editfirmuser');
Route::post('/firmuser/store1', 'Site\ClientController@storeFirmuser')->name('firmuser.store1');
Route::patch('/firmuser/{id}/update1', 'Site\ClientController@updateFirmuser')->name('firmuser.update1');

// Skill Controller
Route::post('/profile/skills/store', 'Site\SkillController@storeSkill');
Route::post('/profile/skills/edit', 'Site\SkillController@editSkill');
// Education Controller
Route::post('/profile/education/store', 'Site\EducationController@storeEducation');
Route::post('/profile/education/update', 'Site\EducationController@updateEducation');
Route::post('/profile/education/delete', 'Site\EducationController@deleteEducation');

//training
Route::post('/profile/training/store', 'Site\TrainingController@storeTraining');
Route::post('/profile/training/update', 'Site\TrainingController@updateTraining');
Route::post('/profile/training/delete', 'Site\TrainingController@deleteTraining');
// Work Controller
Route::post('/profile/work/store', 'Site\WorkController@storeWork');
Route::post('/profile/work/update', 'Site\WorkController@updateWork');
Route::post('/profile/work/delete', 'Site\WorkController@deleteWork');
// Applicant Controller
Route::delete('/panel/jobs/delete/{id}', 'Site\AdminController@deleteJob');

Route::get('contact-us', 'Site\AdshowController@contactUs')->name('contact-us');
Route::post('mcontact/store', 'Site\McontactController@store')->name('mcontact.store');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('freelancers', 'Site\FreelancersController@index')->name('freelancers.index');
Route::get('freelancers/category/{slug}', 'Site\FreelancersController@category')->name('freelancers.category');
Route::get('projects/{slug}', 'Site\FreelancersController@show')->name('freelancers.show');
Route::get('freelancers-search', 'Site\FreelancersController@search')->name('freelancers.search');
Route::get('works', 'Site\FreelancersController@allWorks')->name('works.index');
Route::get('/freelancers/all-categories', 'Site\FreelancersController@allCategories');
Route::get('freelancers/skill/{slug}', 'Site\FreelancersController@skill')->name('freelancers.skill');
Route::get('freelancers/user/{slug}', 'Site\FreelancersController@user')->name('freelancers.user');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::resource('project', 'Site\ProjectController')->except('show');
    Route::post('freelancers/applicant/store', 'Site\FreelancersController@applicantStore')->name('freelancers.applicant.store');
    Route::get('/fshortlist/{slug}', 'Site\FreelancersController@shortlist');
    Route::get('/fproposal/{slug}/{user_id}', 'Site\FreelancersController@proposal');
    Route::get('/fproposal/{id}/{user}/hire', 'Site\FreelancersController@hire');
    Route::get('/fproposal/{id}/{user}/reject', 'Site\FreelancersController@reject');
});

Route::resource('cart', 'Site\CartController')->except('show');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('checkout', 'Site\CheckoutController@index');
    Route::get('bank-transfer', 'Site\BankTransferController@index')->name('bank-transfer.index');
    Route::post('bank-transfer', 'Site\BankTransferController@store')->name('bank-transfer.store');
    Route::get('addresses', 'Site\AddressController@index');
    Route::post('addresses/store', 'Site\AddressController@store')->name('addresses.store');
    Route::delete('addresses/delete/{id}', 'Site\AddressController@destroy')->name('addresses.destroy');

    Route::get('order', 'Site\OrderController@index')->name('order');
});

Route::get('orderAdmin', 'Site\AdminController@orderAdmin')->name('orderAdmin');
Route::get('cancelOrder/{id}', 'Site\AdminController@cancelOrder')->name('cancelOrder');
Route::post('cancelOrderRequest/{id}', 'Site\AdminController@cancelOrderRequest')->name('cancelOrderRequest');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth', 'verified']], function () {

    Route::post('images/upload', 'Admin\ProductImageController@upload')->name('admin.products.images.upload');

app/OrderStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Order;

class OrderStatus extends Model
{
    protected $fillable = [
        'name',
        'color',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    public function orders()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/Admin/OrderStatusController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Contracts\OrderStatusContract;
use App\Http\Controllers\BaseController;

class OrderStatusController extends BaseController
{
    private $page="admin.orderstatus.";

    protected $orderstatusRepo;

    public function __construct(
        OrderStatusContract $orderstatusRepo
    )
    {
        $this->orderstatusRepo = $orderstatusRepo;
    }

    public function index()
    {
        $list = $this->orderstatusRepo->list('created_at', 'desc');
        $datas = $this->orderstatusRepo->paginateArrayResults($list->all(), 15);
        $this->setPageTitle('orderstatus', 'List of orderstatuss');
        return view($this->page.'index',compact('datas'));
    }

    public function create()
    {
        $this->setPageTitle('orderstatus', 'Create orderstatus');
        return view($this->page.'create');
    }

    public function store(Request $request)
    {
        $data = $this->orderstatusRepo->store($request);

        if (!$data) {
            return $this->responseRedirectBack('Error occurred while creating record.', 'error', true, true);
        }
        return $this->responseRedirect('orderstatus.index', 'Record added successfully' ,'success',false, false);
    }

    public function edit($id)
    {
        $data = $this->orderstatusRepo->findById($id);
        $this->setPageTitle('orderstatus', 'Edit orderstatus');
        return view($this->page.'edit', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $data = $this->orderstatusRepo->edit($request, $id);

        if (!$data) {
            return $this->responseRedirectBack('Error occurred while updating record.', 'error', true, true);
        }
        return $this->responseRedirect('orderstatus.index', 'Record updated successfully' ,'success',false, false);
    }

    public function destroy($id)
    {
        $data = $this->orderstatusRepo->destroy($id);

        if (!$data) {
            return $this->responseRedirectBack('Error occurred while deleting record.', 'error', true, true);
        }
        return $this->responseRedirect('orderstatus.index', 'Record deleted successfully' ,'success',false, false);
    }
}

resources/views/admin/orderstatus/base.blade.php
@extends('admin.layouts.app-template')
@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
      {{ $pageTitle }}
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Details</a></li>
        <li class="active">{{ $pageTitle }}</li>
      </ol>
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/orderstatus/create.blade.php
@extends('admin.orderstatus.base')

@section('action-content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{$subTitle}}</div>
                <div class="panel-body">
                    <form method="POST" action="{{ route('orderstatus.store') }}" aria-label="category" enctype="multipart/form-data">
                        {{csrf_field()}}

                <div class="form-group">
                    <label for="name">Name</label>
                    <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="color">Color</label>
                    <input class="form-control jscolor" type="text" name="color" id="color" value="{{ old('color') }}">
                </div>
                
                    
                        
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Create
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/orderstatus/edit.blade.php
@extends('admin.orderstatus.base')

@section('action-content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{$subTitle}}</div>
                <div class="panel-body">
                    <form method="POST" action="{{ route('orderstatus.update',$data->id) }}" aria-label="category" enctype="multipart/form-data">
                        {{csrf_field()}}
                        {{method_field('PATCH')}}

                <div class="form-group">
                    <label for="name">Name</label>
                    <input class="form-control" type="text" name="name" id="name" value="{{ $data->name ?: old('name') }}" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="color">Color</label>
                    <input class="form-control jscolor {hash:true}" type="text" name="color" id="color" value="{{ $data->color ?: old('color') }}">
                </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/orderstatus/index.blade.php
@extends('admin.orderstatus.base')
@section('action-content')
    <!-- Main content -->
    <section class="content">
      <div class="box">
  <div class="box-header">
    <div class="row">
        <div class="col-sm-8">
          <h3 class="box-title">{{$subTitle}}</h3><br>
        </div>
        <div class="col-sm-4">

          @include('admin.partials.flash')
          <a class="btn btn-primary" href="{{route('orderstatus.create')}}">Add </a>
        </div>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
      <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-6"></div>
      </div>
      
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
      <div class="row">
        <div class="col-sm-12">
          <table id="example3033" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
              <tr role="row">
                <th width="2%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="city: activate to sort column ascending">ID</th>
                <th width="10%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="city: activate to sort column ascending">Name</th>
                <th width="10%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="city: activate to sort column ascending">Colour</th>
                
                <th tabindex="0" aria-controls="example2" rowspan="1" colspan="2" aria-label="Action: activate to sort column ascending">Action</th>
              </tr>
            </thead>
            <tbody>
            @foreach($datas as $value)  
                <tr data-address-id="{{ $value->id }}" role="row" class="odd">
                  <td>{{$value->id}}</td>
                  <td>{{ $value->name }}</td>
                            <td><button class="btn" style="background-color: {{ $value->color }}"><i class="fa fa-check" style="color: #ffffff"></i></button></td>
                  <td> 
                        <a href="{{ route('orderstatus.edit',$value->id)}}" class="btn btn-warning col-sm-3 col-xs-5 btn-margin">
                        <i class="fa fa-pencil-square-o large"></i>
                        </a>
                    <form class="row" method="POST" action="{{ route('orderstatus.destroy', $value->id) }}" onsubmit = "return confirm('Are you sure?')">
                      {{csrf_field()}}
                      {{method_field('DELETE')}}
                      <button type="submit" class="btn btn-danger col-sm-3 col-xs-5 btn-margin">
                        <i class="fa fa-trash large"></i>
                      </button>
                      </form>
                  </td>
              </tr>
        @endforeach
            </tbody>
          </table>
          
        </div>
      </div>
      </div>
    </div>
  </div>
  <!-- /.box-body -->
</div>
    </section>
    <!-- /.content -->
  </div>
@endsection